version: '3'

services:
  keycloak:
    container_name: keycloak
    command: start-dev
    depends_on:
      postgres:
        condition: service_started
    environment:
      KC_DB: postgres
      KC_DB_PASSWORD: password
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_HOSTNAME: localhost
      KC_PROXY: edge
      # THESE ARE THE NEW LINES YOU NEEDED:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    hostname: keycloak
    image: quay.io/keycloak/keycloak:latest
    networks:
      default: null
      postgresql: null
    restart: always
    ports:
      - "8080:8080"
    volumes:
    - type: bind
      source: ./keycloak_providers
      target: /opt/keycloak/providers
      bind:
        create_host_path: true

  postgres:
    hostname: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      postgresql: null
    restart: always
    volumes:
    - type: bind
      source: ./postgres_data
      target: /var/lib/postgresql/data
      bind:
        create_host_path: true

networks:
  default:
    name: docker-stack_default
  postgresql:
